Hooks:Add("LocalizationManagerPostInit", "WE_GOTTA_GET_BAIN_BACK", function(loc)
	LocalizationManager:add_localized_strings({
		-- Informações da Heist e o nome
		heist_bph = "A Ilha do Inferno",
		heist_bph_crimenet = "Pessoal, o Elephant me ajudou com algumas informações, e eu conseguir localizar o Bain. os merdinhas do Kataru prederam ele em uma prisão abandonada da Segunda Guerra Mundial. A prisão está localizado em uma ilha em águas internacionais ao largo costa norte do Oregon e foi usado pelos Murkies desde os anos 70. Fiz alguns favores e comprei um ingresso pra você em um pequeno submarino urbano, para que você pode entrar sem ninguém te ver no local e trazer o nosso amigo de volta. \n\n»Entra na prisão \n»Localize Bain \n»Liberte Bain e escape",
		
		-- Outros
		heist_bph_hl = "A Ilha do Inferno",
		
		-- In Briefing
		heist_bph_briefing = "Ok, agora, nós não sabemos onde exatamente o Bain está na prisão ou a condição que ele está, e tem muitos Murkys por toda parte. Esse vai ter que ser barulhento e rápido, okay? Vocês estarão indo pelo o sistema de esgoto que deságua no oceano.",
		
		-- Introdução
		rb1_bph_intro_03a = "Chains: Sente familiar, Hox?",
		rb5_bph_intro_03b = "Hoxton: Tudo isso aconteceu antes. Que merda.",
		rb1_bph_intro_03c = "Duke: Quem matar o Kento, vai ter que pagar um drink.",
		rb22_bph_intro_03d = "Duke: Fica de olho nessas coisas que brilham verde.",
		rb1_bph_intro_03e = "Chains: E as grande malditas explosões, certo?",
		rb5_bph_intro_03f = "Hoxton: Caçadores da punheta perdida.",
		rb1_bph_intro_03g = "Chains: É, filme errado, Hox.",
		rb1_bph_intro_04b = "Chains: Pois é, nem é doce.",
		rb22_bph_intro_04c = "Duke: Será que alguém lembrou de trazer capas de chuva, em caso da a gente precisar fazer uma jangada?",
		rb1_bph_intro_04d = "Chains: Segura aí, Bain. Nós estamos chegando.",
		rb22_bph_intro_04aa = "Duke: Eu tenho um mal pressentimento sobre isso. Deveria ter um mal pressentimento sobre isso?",
		rb5_bph_intro_04a = "Hoxton: Ah, caralho. O cheiro desse lugar...",
		rb1_bph_intro_02f = "Chains: Hora de vira as mesas.",
		rb22_bph_intro_02e = "Duke: Esgoto. Porque tinha que ser esgoto.",
		rb1_bph_intro_02d = "Chains: Conveniente pra caralho, esse escoderijo da Murkywater.",
		rb22_bph_intro_02c = "Duke: Lugar aconchegante, né?",
		rb5_bph_intro_02b = "Hoxton: Eu espero que aquele merdinha do Kento aparece. Eu REALMENTE espero.",
		rb22_bph_intro_02a = "Duke: Bain, velho amigo, aqui vamos nós! Oh, que poesia boa.",
		
		-- Legendas
		loc_bph_end_fail_01 = "Amigos, não era pra gente ter falhado... nada bom, nada bom...",
		loc_bph_03_01 = "Merda! Porra de Murky!",
		loc_bph_11_01 = "Muito bem, ver se você consegue ver o Bain pelas as cameras de segurança.",
		loc_bph_12a_02 = "Ali está! Hein... ele não parece bem, amigos. Liberte ele.",
		loc_bph_12_03 = "Ache a cela do Bain pelas as cameras.",
		loc_bph_12_01 = "Vamos, amigos. Ver pelas as cameras.",
		loc_bph_12_02 = "Você tem que usar as cameras para achar o Bain!",
		loc_bph_15_01 = "Bom, agora relaxe um pouco.",
		loc_bph_16_01 = "Para onde ele ta indo? A lavandeira? Segue ele, seus idiotas!",
		loc_bph_17_03 = "Depressa, vocês tem que seguir Bain!",
		loc_bph_24_02 = "Vai pro telhado!",
		loc_bph_29_01 = "Ach, eu não consigo chegar até no heliporto. Vocês tem que extender a ponte. Ache a sala de controles.",
		loc_bph_31_01 = "Descansar pra eu respirar. Não vai ser bom se eu desmaiar com Bain",
		loc_bph_33_01 = "Ok, agora abre essas porta. Deve ser uma caixa de controle que você pode hackiar.",
		loc_bph_35_04 = "Ok, vamos levar o Bain pro helicóptero, e então, nós podemos sair desse maldito lugar!",
		loc_bph_36_01 = "Depressa, amigos!",
		loc_bph_03_02 = "Emboscada! Mate eles!",
		loc_bph_06_03 = "Vamos, amigos, vai pro bloco de celas.",
		loc_bph_06_02 = "O quê vocês estão esperando? vai pro bloco de celas!",
		loc_bph_07_02 = "É o lugar, mas você vai ter que entra na sala de controle.",
		loc_bph_11_03 = "Agora use as cameras de segurança e tenta localizar a cela do Bain.",
		loc_bph_18_03 = "Eles está indo pra cantina, vocês tem que seguir ele!",
		loc_bph_19_02 = "Segue Bain para a cantina!",
		loc_bph_23_01 = "Bain está indo pro telhado, tenta seguir ele, okay?",
		loc_bph_29_03 = "Merda, não consigo chegar até no helicóptero, a menos se você extender a ponte. Ache a sala de controle e extenda ela.",
		loc_bph_26_03 = "Limpa o caminho, eu to com o Bain!",
		loc_bph_31_03 = "Me dá um momento, tenho que descansar",
		loc_bph_32_01 = "Ah! Esses caras estão muito perto!",
		loc_bph_33_03 = "Eu não consigo passar por essa porta. Parece que é automatica, ache uma caixa de controle e hackeia.",
		loc_bph_34_03 = "Hackeia a caixa de controle!",
		loc_bph_01_02 = "Hora da gente ter o nosso Bain de volta. Vamos.",
		loc_bph_04a_02 = "Que grande merda, né?",
		loc_bph_05_01 = "Muito bem. Agora vamos descubrir onde o Bain está. Vai pro bloco de celas.",
		loc_bph_06_01 = "Você precisa ir até pro bloco de celas, aogra.",
		loc_bph_09_03 = "Seria bom cortar essas barras, se você puder acha alguma coisa.",
		loc_bph_10_02 = "Sem tempo a perder, corte essas barras, assim que possível.",
		loc_bph_10_01 = "Você tem que cortar essa barras.",
		loc_bph_10_03 = "O velho Locke não pode fazer isso pra você. Adna logo!",
		loc_bph_01_03 = "Nós não podemos ferrar isso, nós temos que fazer isso, e respeitável.",
		loc_bph_01_01 = "Ok, amigos, isso foi a muito tempo atrás. Hora da vingança, okay?",
		loc_bph_02_02 = "Ver se você consegue ir pro proximo andar. deve ter uma escotilha ou algo do tipo. os Murky podem não ta nos esperando, mas fica pronto pra qualquer coisa.",
		loc_bph_03_03 = "Cuidado, gente!",
		loc_bph_04a_01 = "Filha da puta! Eu gostaria de chutar no dente dele!",
		loc_bph_05_03 = "Boa. Agora, ver se você achar o bloco de celas.",
		loc_bph_07_01 = "Ok, Agora você terá que ir pra sala de controle.",
		loc_bph_08_01 = "Aquele termite que você pegou antes, deve funcionar.",
		loc_bph_11_12 = "Bom, agora use as cameras para localizar a cela do Bain.",
		loc_bph_12a_03 = "Ok, é esse, ali está ele! Liberta ele, okay?",
		loc_bph_15_03 = "Boa, agora, espere a cela dele abrir.",
		loc_bph_16_03 = "Eles está indo pra lavandeira. Segue ele!",
		loc_bph_20_03 = "Caralho! Bain deu uma bela surra, né? Coloca a furadeira na porta e pega as chaves!",
		loc_bph_17_02 = "Não fica aí parado, segue ele!",
		loc_bph_23_03 = "Muito bom, amigos. Agora segue Bain até no telhado!",
		loc_bph_24_03 = "Você tem que chegar até no telhado!",
		loc_bph_26_02 = "Ele é muito pesado do que eu achava! Vamos!",
		loc_bph_29_02 = "Esse caminho está bloqueiado. Você tem que acha os controles e extender a ponte!",
		loc_bph_26_01 = "Eu to com ele. Vamos sair desse maldito lugar.",
		loc_bph_31_02 = "Eu preciso de um descanso. Bain é muito pesado, ta bom?",
		loc_bph_32_03 = "Mantenha esses babacas longe!",
		loc_bph_33_02 = "Arg, outro maldito problema. Ache a caixa de controle e hackeia, e poderemos atravesar.",
		loc_bph_35_03 = "Hora de sair daqui, amigos! Entra no helicóptero.",
		loc_bph_36_03 = "Sem tempo a perder, temos que sair daqui!",
		loc_bph_05_02 = "Boa, amigos, agora vai pro bloco de celas e achar o Bain e libertar ele.",
		loc_bph_07_03 = "Você precisa achar um jeito de chegar até na sala de controle, ta bom?",
		loc_bph_08_03 = "Use o termite que você pegou. Isso deve ajudar a corta as barras.",
		loc_bph_12a_01 = "É esse, bem ali! Agora liberte ele.",
		loc_bph_15_02 = "Agora espere que a cela dele abre.",
		loc_bph_21_02 = "Você tem que usar a furadeira na porta",
		loc_bph_32_02 = "Eles estão quase em nós, pessoal!",
		loc_bph_35_01 = "Boa, agora, vamos pro helicóptero. Não consigo carregar ele por muito tempo.",
		
		--
	})
end)